name: Typescript Package

on:
  push:
    branches:
      - dev
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
        with:
          repository: DyshliukRostyslav/frontend-ts
          token: ${{ secrets.Rostyslav }}
          ref: dev
      - uses: action/setup-node@v1
        with:
          node-version: 12
          registy-url: https://npm.pkg.github.com/
          scope: 'DyshliukRostyslav'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.Rostyslav}}
