name: Publish Core Package

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@DyshliukRostyslav'
      - run: npm ci
        working-directory: ./core
      - run: git config --global user.name 'Edenlab Tech'
        working-directory: ./core
      - run: git config --global user.email 'tech@edenlab.com.ua'
        working-directory: ./core
      - run: npm version patch -m "RELEASE Core package %s"
        working-directory: ./core
      - run: git push "https://${{ secrets.NPM_AUTH_TOKEN }}@github.com/${{ github.repository }}"
        working-directory: ./core
      - run: npm publish --registry=https://npm.pkg.github.com/
        working-directory: ./core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
