name: Publish CI

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@DyshliukRostyslav'
      - run: npm ci
      - run: git config --global user.name 'Edenlab Tech'
      - run: git config --global user.email 'tech@edenlab.com.ua'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push
      - run: npm publish --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
